### ISSUE TITLE
ChecksumMismatchError: SHA256 mismatch when installing adoptopenjdk-openjdk11

### ISSUE THREAD

**Issue by dcommander** [AdoptOpenJDK/homebrew-openjdk#27]
```
==> Installing adoptopenjdk-openjdk11 from adoptopenjdk/openjdk
==> Downloading https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/down
Already downloaded: /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/154143ed1f7540b66ebceb732063de00c27467a5796256bea5e4492690833116--OpenJDK11-jdk_x64_mac_hotspot_11_28.tar.gz
Error: An exception occured within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 809a797d72a78668095913cdb2b39d1cf03ab76d144fd9a660031e4f604165ab
Actual: e99866dfaf2b245a966b2d1e83a76b4f6f13727859c37ee248eb6c763951e536
Archive: /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/154143ed1f7540b66ebceb732063de00c27467a5796256bea5e4492690833116--OpenJDK11-jdk_x64_mac_hotspot_11_28.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by karianna** [comment]
fixed in #28

**Comment by IshanRattan** [comment]
Still not fixed, same issue

==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk11u/archive/jdk-11.0.
==> Downloading from https://hg.openjdk.org/jdk-updates/jdk11u/archive/jdk-11.0.
                                                #     #  -=#=-  #             
Error: SHA256 mismatch
Expected: 0f35778a120da24dff1f752d128029d87448777a6ab9401c7cf5bc875f127d80
  Actual: c30e0bf48418d9e5b63ad991351f61d4020e6e52bfca9aa5c3557f6a9a90dcdc
    File: /Users/user/Library/Caches/Homebrew/downloads/841adb42e2976e35af75bb87be6dd9c56fe0d4d29a499e4b731d245f4c476626--jdk11u-jdk-11.0.9-ga.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by gdams** [comment]
> Still not fixed, same issue
> 
> ==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk11u/archive/jdk-11.0. ==> Downloading from https://hg.openjdk.org/jdk-updates/jdk11u/archive/jdk-11.0. # # -=#=- # Error: SHA256 mismatch Expected: 0f35778a120da24dff1f752d128029d87448777a6ab9401c7cf5bc875f127d80 Actual: c30e0bf48418d9e5b63ad991351f61d4020e6e52bfca9aa5c3557f6a9a90dcdc File: /Users/user/Library/Caches/Homebrew/downloads/841adb42e2976e35af75bb87be6dd9c56fe0d4d29a499e4b731d245f4c476626--jdk11u-jdk-11.0.9-ga.tar.bz2 To retry an incomplete download, remove the file above.

Those binaries from hg.openjdk.java.net are nothing to do with us. Please use the `temurin` image
